# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./udagram-reverseproxy
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-feed ./udagram-api-user
- docker build -t udagram-api-feed ./udagram-frontend
# Do similar for other three images

# Tagging
- docker build -t udagram-reverseproxy ./udagram-reverseproxy
- docker tag udagram-api-feed 898969/udagram-api-feed:v1
- docker tag udagram-api-user 898969/udagram-api-user:v1
- docker tag udagram-frontend 898969/udagram-frontend:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push 898969/udagram-reverseproxy:v1
- docker push 898969/udagram-api-feed:v1
- docker push 898969/udagram-api-user:v1
- docker push 898969/udagram-frontend:v1
# Do similar for other three images