# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
language: node_js

node_js:
  - 13

services:
  - docker

install:
  - echo "there's nothing to be installed"

before_script:
  - echo "no tests"

script:
  - docker-compose -f docker-compose-build.yaml build --parallel
  # - docker build -t udagram-api-feed ./udagram-api-feed
  # - docker build -t udagram-api-feed ./udagram-api-user
  # - docker build -t udagram-api-feed ./udagram-frontend
  # Do similar for other three images

  # # Tagging
  # - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # - docker tag udagram-api-feed 80804l/udagram-api-feed:v1
  # - docker tag udagram-api-user 80804l/udagram-api-user:v1
  # - docker tag udagram-frontend 80804l/udagram-frontend:v1
  # # Do similar for other three images


after_success:
  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker-compose-build.yaml push
  # - docker push 80804l/udagram-reverseproxy:v1
  # - docker push 80804l/udagram-api-feed:v1
  # - docker push 80804l/udagram-api-user:v1
  # - docker push 80804l/udagram-frontend:v1
  # Do similar for other three images
